### ISSUE TITLE
Replay folders without a player name

### ISSUE THREAD

**Issue by Krambed** [thecolonel63/server-side-replay-recorder#1]
I noticed these while going through the recordings folder. The regular player folders are there and this screenshot is taken at a time with two players online.

![image](https://user-images.githubusercontent.com/85061776/174295930-979eda9c-6ef0-47b5-a51f-49adc9387c6a.png)

**Comment by thecolonel63** [comment]
This happens because the zipping process was interrupted before the recordings could finish zipping into mcpr files, due to the server shutting down because of either a crash or an intentional shutdown. 

I will attempt to patch this when time allows such that when the server is starting it will first attempt to fix them.

Thank you for your report.

**Comment by thecolonel63** [comment]
Fixed with the latest release.
