### ISSUE TITLE
Crash on my fabric 0.14.21 server 1.20.1

### ISSUE THREAD

**Issue by thejekky** [thecolonel63/server-side-replay-recorder#41]
Hello, i tried to use this mod on my falixnodes server and keep getting a crash with it, if i remove the mod the server boots up and runs fine, theres probably a mod conflict here but idk which also im using mixintrace, heres the crash report
[crash-2023-09-03_16.14.28-server.txt](https://github.com/thecolonel63/server-side-replay-recorder/files/12507194/crash-2023-09-03_16.14.28-server.txt)

edit: here it is on mclo.gs https://mclo.gs/F6BQOFi

**Comment by thecolonel63** [comment]
Hi! This is due to an incompatibility with an optimization that Very Many Players is using.

To fix this, you can either uninstall Very Many Players, or you can uninstall Server Side Replay Recorder, as compatibility between the two mods is not planned as of right now.

**Comment by thejekky** [comment]
Oh alright, good to know

**Comment by thejekky** [comment]
it would be a good idea to say somewhere in the modrinth page or something that VMP is broken with this mod btw

**Comment by thecolonel63** [comment]
Yeah I know - I just can't release any updates as of right now because I want to refrain from updating the mod until I can properly backport it to older versions. I've had at least 5 different issues appear that can't be solved right now because they're in older versions of the mod, and I don't want to need to maintain several different feature branches at the same time for one mod.
