### ISSUE TITLE
How to view replays

### ISSUE THREAD

**Issue by dotmrjosh** [thecolonel63/server-side-replay-recorder#46]
I feel dumb asking this but I've been shuffling files around for hours and the replays copied from the server aren't appearing in the replay viewer. Is there a guide on how I'm supposed to copy things and what goes where? I'd be happy to make a PR with a README for this once everything is explained :)

**Comment by thecolonel63** [comment]
Hi.

Can you attach one of the generated files so I can test it, just to make sure the files aren't corrupt?

**Comment by mattymatty97** [comment]
by default you'll find the replay files under `$server_folder/replay_recordings`,
and you have to copy the file into the `replay_recordings` folder that is on your client (`%appdata%/.minecraft/replay_recordings`)
🤔

**Comment by mattymatty97** [comment]
you can also get the recordings with the command `/replay file [player/region] upload [filename]` and the mod should respond with a web link to download the file

**Comment by dotmrjosh** [comment]
> copy the file into the replay_recordings folder that is on your client

I did try that so maybe sounding like corruption? Would certain mods cause issues or break things? I couldnt find any sign of issues in logs.

[replays.zip](https://github.com/thecolonel63/server-side-replay-recorder/files/13344487/replays.zip)

**Comment by dotmrjosh** [comment]
> you can also get the recordings with the command `/replay file [player/region] upload [filename]` and the mod should respond with a web link to download the file

Also i didnt realize the upload command meant upload to a file service for download. I thought it meant uploading local replays to the server for some reason so thanks for clarification :)

**Comment by thecolonel63** [comment]
I just copied the file into my replay viewer and it's showing up in the list fine - are you making sure to take the file out of the "player/dotmrjosh/" folder before copying it to the "replay_recordings" folder?

**Comment by dotmrjosh** [comment]
Hmm i can't recreate the issue now. Before it would generate a folder labeled "recordings_83762945" (the numbers would be random). Do you have a process for checking if a recording is corrupted that I could use to come back with later?

**Comment by thecolonel63** [comment]
It's generating that folder because it's a temp folder used for storing the replay data before it gets compressed into the replay file, meaning if it appears like that it means it's either currently in the process of compressing the recording to the .mcpr format or it was interrupted with a server shutdown.

Currently the way of checking if a replay is corrupted is by looking at the .mcpr file and opening it with a file archiver like 7-zip or winrar to ensure that it internally contains "recording.tmcpr" and "metaData.json".

Also as I have previously stated the replay you sent seems to work fine in the replay viewer, so I would just like to confirm that it works on your end if you move the file from "server_folder_here/replay_recordings/player/dotmrjosh/filenamehere.mcpr" to "minecraft_client_folder_here/replay_recordings/filenamehere.mcpr"

**Comment by dotmrjosh** [comment]
Yes, sorry if I didn't clarify its working on my end now. My current guess then is that the server shutdown too soon before the recording was fully saved but thanks for the insight on how to debug recordings. Am happy to close this for now and will update if something resurfaces. Thanks for your time.
